Repository business-factory/captain-hook, pull requests merged in 2018-08, with the labels that each got.

#29 Gunicorn with eventlet workers. Max connections per worker set to 10.
  hooks/publisher.py
  hooks/settings/settings_gunicorn.py
  requirements.txt
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-miso, waiting-review-roman

#31 Increase Gunicorn worker eventlet connections, 10 -> 100.
  hooks/settings/settings_gunicorn.py
Labels: waiting-review-jiri, waiting-review-miso

#32 Feature pipenv
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  requirements.txt
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-mato, waiting-review-roman

#33 Increase Gunicorn worker connections, 100 -> 1000
  hooks/settings/settings_gunicorn.py
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-miso, waiting-review-roman
