Repository business-factory/captain-hook, pull requests merged in 2018-09, with the labels that each got.

#34 Forward messages from Hubspot to both master & staging Rabbit #25196
  hooks/api_server.py
  hooks/services.py
  hooks/settings/__init__.py
  hooks/settings/_settings_default.py
  hooks/settings/_settings_master.py
  hooks/settings/_settings_staging.py
  kubernetes/captain-hook-master-deployment.yaml
  kubernetes/captain-hook-staging-deployment.yaml
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-miso, waiting-review-roman

#35 Log only to GL on production & use requests patched by eventlet
  hooks/api_server.py
  hooks/services.py
  requirements.txt
Labels: bug, waiting-review-dave, waiting-review-jiri, waiting-review-miso, waiting-review-roman

#37 Move and rename Jenkins deploy scripts
  jenkins/pipeline/deploy-master.groovy
  jenkins/pipeline/deploy-staging.groovy
Labels: waiting-review-dave, waiting-review-mato, waiting-review-miso, waiting-review-roman
