Repository business-factory/captain-hook, pull requests merged in 2018-04, with the labels that each got.

#17 Staging kubernetes deploy
  jenkins-staging.groovy
  kubernetes/captain-hook-staging-deployment.yaml
  kubernetes/captain-hook-staging-service.yaml
Labels: waiting-review-dave, waiting-review-jiri, waiting-review-mato, waiting-review-miso, waiting-review-pista, waiting-review-roman

#18 Remove --use-wheel flag
  Dockerfile
  README.md
Labels: bug, waiting-review-dave, waiting-review-mato, waiting-review-miso, waiting-review-pista, waiting-review-roman

#20 Dev to Master
  jenkins-staging.groovy
  kubernetes/captain-hook-staging-deployment.yaml
  kubernetes/captain-hook-staging-service.yaml
Labels: waiting-review-dave, waiting-review-mato, waiting-review-miso, waiting-review-pista, waiting-review-roman
